spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pizza?useSSL=false
    username: postgres
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
#    change-log: classpath:migration/users.yml
    enabled: false




